require 'trung.config.options'
require 'trung.config.autocmds'
require 'trung.config.keymaps'
require 'trung.config.filetypes'
require 'trung.config.extras.marks'
require 'trung.config.extras.highlight_calls'
